### PR TITLE
Adds @method and @mixin annotations to Table plus other fixes

### LINKED ISSUE #237: Add @method stubs for tables to declare return type.
When you generate a `Table` with bake. You get a class phpDoc like this.

For example, `PostsTable` with some associations.

```
/**
 * Posts Model
 *
 * @property \Cake\ORM\Association\HasMany $PostLikes
 * @property \Cake\ORM\Association\HasMany $PostViews
 * @property \Cake\ORM\Association\BelongsToMany $Boards
 */
```

Afterwards when you want to use `get` or `newEntity` you have to do this to get proper type auto-complete.

```
    /**
     * @type \App\Model\Entity\Post $post
     */
    $post = $this->Posts->get($id);
```

It peppers the source code with type declares and is a pain to always write. So what I do is declare the return types using `@method`. Like this

```
/**
 * Posts Model
 *
 * @property \Cake\ORM\Association\HasMany $PostLikes
 * @property \Cake\ORM\Association\HasMany $PostViews
 * @property \Cake\ORM\Association\BelongsToMany $Boards
 *
 * @method get($primaryKey, $options = []) : Post
 * @method newEntity($data = null, array $options = []) : Post
 * @method patchEntity(EntityInterface $entity, array $data, array $options = []) : Post
 */
```

Now auto-complete works in the IDE

```
     $this->Posts->get($id)->title;   <-- title marked as property from Post entity.
```

There are other methods from the table that could use this trick as well. Like "save", "newEntities", etc. Any method where the return type is the `EntityInterface`

Would this be something worth adding to the bake plugin?

### LINKED ISSUE #238: Add @mixin for tables that use behaviors.
To expand on #237 that adds return stubs. This improvement would add mixins for behaviors.

If bake adds the `TimestampBehavior` it should also add the `@mixin` for that behavior to the class.

```
/**
 * Posts Model
 *
 * @property \Cake\ORM\Association\HasMany $PostLikes
 * @property \Cake\ORM\Association\HasMany $PostViews
 * @property \Cake\ORM\Association\BelongsToMany $Boards
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
```

This would give you auto-complete on all the public functions from that behavior on the table.

```
    $this->Posts->touch($post); // <- IDE sees touch as valid method of Posts
```

Without the `@mixin` the IDE will mark `touch` as invalid method for that class.

### PR DESCRIPTION
**Pull request by thinkingmedia**
This PR closes #237 and closes #238 

Updates the baking for Table

- @method stubs that declare return type are added to Table classes, ~~but only for PHP7~~
- @mixin are added to Table classes for behaviors, ~~but only for PHP7~~

Updates the baking for Entity

- @property for table columns are listed first
- @property for associations are listed last
- trailing comma on $_accessible fixed.

General updates

- Both Table and Entity now use DocBlock helper to write class description.
- ~~for tests that differ on PHP7 you can just add a "7" to the end of the comparison file.~~
- added declaration of properties for unit tests

~~This is the first time that Bake will render different results based upon the PHP version. If you are using PHP7 the @method stubs for Table will be added, otherwise everything works as it did before.~~

~~There isn't a way to configure Bake per project. I would like to open a issue to add config support and then make PHP7 behavior configurable.~~

### CODE REVIEW

**Comment by thinkingmedia** [comment]
Forgot to mention that PHP7 and PHP5 differences are part of the travis tests.

File: src/Shell/Task/ModelTask.php [hunk 1]
```diff
@@ -173,7 +173,7 @@ public function all()
     public function getTableObject($className, $table)
     {
         if (TableRegistry::exists($className)) {
-            return TableRegistry::get($className);
+                return TableRegistry::get($className);
```
Comment (markstory) [inline src/Shell/Task/ModelTask.php]: Indentation looks wrong.

File: src/Template/Bake/Model/entity.ctp [hunk 2]
```diff
@@ -63,11 +55,7 @@ class <%= $name %> extends Entity
      *
      * @var array
      */
-    protected $_accessible = [
-<% foreach ($accessible as $field => $value): %>
-        '<%= $field %>' => <%= $value %>,
-<% endforeach; %>
-    ];
+    protected $_accessible = [<%= $this->Bake->stringifyList($accessible,['quotes'=>false]) %>];
```
Comment (markstory) [inline src/Template/Bake/Model/entity.ctp]: You need spaces around the `,` and `=>`.

File: src/Template/Bake/Model/table.ctp [hunk 3]
```diff
@@ -13,6 +13,29 @@
...
+if(PHP_MAJOR_VERSION >= 7)
+{
+    $annotations[] = "@method get(\$primaryKey, \$options = []) : {$entity}";
+    $annotations[] = "@method newEntity(\$data = null, array \$options = []) : {$entity}";
+    $annotations[] = "@method newEntities(array \$data, array \$options = []) : {$entity}[]";
+    $annotations[] = "@method save(EntityInterface \$entity, \$options = []) : {$entity}";
+    $annotations[] = "@method patchEntity(EntityInterface \$entity, array \$data, array \$options = []) : {$entity}";
+    $annotations[] = "@method patchEntities(\$entities, array \$data, array \$options = []) : {$entity}[]";
+    foreach ($behaviors as $behavior => $behaviorData)
+    {
```
Comment (markstory) [inline src/Template/Bake/Model/table.ctp]: Should be `foreach (...) {`.

File: src/Template/Bake/Model/table.ctp [hunk 4]
```diff
@@ -25,22 +48,16 @@ $uses = [
     'use Cake\ORM\Table;',
     'use Cake\Validation\Validator;'
 ];
+if(PHP_MAJOR_VERSION >= 7)
+{
```
Comment (markstory) [inline src/Template/Bake/Model/table.ctp]: Should be `if (...) {`

File: src/View/Helper/DocBlockHelper.php [hunk 5]
```diff
@@ -1,14 +1,52 @@
...
+                }
+                $previous = $type;
+            }
+            $lines[] = $ann;
+        }
+
+        $lines = array_merge(["/**"], (new Collection($lines))->map(function ($line) {
+            return rtrim(" * {$line}");
+        })->toArray(), [" */"]);
+        return implode(PHP_EOL, $lines);
```
Comment (markstory) [inline src/View/Helper/DocBlockHelper.php]: This will use `\r\n` on windows. Is that what windows users expect in their source code?

File: tests/TestCase/Php7CompareTrait.php [hunk 6]
```diff
@@ -0,0 +1,48 @@
...
+{
+    use StringCompareTrait {
+        assertSameAsFile as assertSameAsFileBase;
+    }
+
+    /**
+     * Compare the result to the contents of the file based upon which
+     * version PHP is being used.
+     *
+     * The env variable UPDATE_TEST_COMPARISON_FILES will not generate "php7"
```
Comment (markstory) [inline tests/TestCase/Php7CompareTrait.php]: Why are php7 files different?

File: tests/TestCase/Php7CompareTrait.php [hunk 7]
```diff
@@ -0,0 +1,48 @@
...
+     */
+    public function assertSameAsFile($path, $result)
+    {
+        if (!file_exists($path)) {
+            $path = $this->_compareBasePath . $path;
+        }
+
+        if (PHP_MAJOR_VERSION >= 7 && file_exists($path . '7')) {
+            $path = $path . '7';
+        }
```
Comment (markstory) [inline tests/TestCase/Php7CompareTrait.php]: Why?

File: tests/TestCase/Php7CompareTrait.php (hunk 6 above)
Comment (markstory) [inline tests/TestCase/Php7CompareTrait.php]: Are `@method` documentation tags somehow invalid in PHP5?

File: src/Template/Bake/Model/table.ctp (hunk 3 above)
Comment (josegonzalez) [inline src/Template/Bake/Model/table.ctp]: Why is this scoped to PHP7? Do they not work under PHP 5.x?

Comment (thinkingmedia) [inline src/Template/Bake/Model/table.ctp]: @josegonzalez type hinting the return value is PHP7 only.

File: tests/TestCase/Php7CompareTrait.php (hunk 6 above)
Comment (thinkingmedia) [inline tests/TestCase/Php7CompareTrait.php]: @markstory The @method tags use type hinting on the return value which is PHP7 only.

**Comment by thinkingmedia** [comment]
I might be wrong about how I did the return types.

Looks like you can write it the PHP7 way, but you can also write it the PHP5 way.

```
@method Entity get(\$primaryKey, \$options = [])";
```

So I will be updating this PR. If it is not just a PHP7 feature, than I'll remove the PHP7 specific changes.

File: src/Template/Bake/Model/table.ctp (hunk 3 above)
Comment (josegonzalez) [inline src/Template/Bake/Model/table.ctp]: I do not understand what that has to do with annotations though, which should work fine on older versions.

Comment (thinkingmedia) [inline src/Template/Bake/Model/table.ctp]: @josegonzalez On PHP7 its written like this `@method foo() : array` and it doesn't work in PhpStorm is the version is set to PHP 5. But I think if I write like this `@method array foo()` it works in all versions. I'll fix it tomorrow.

File: src/View/Helper/DocBlockHelper.php (hunk 5 above)
Comment (thinkingmedia) [inline src/View/Helper/DocBlockHelper.php]: @markstory I thought using `PHP_EOL` was standard practice? I can change it to `"\n"` if you want.

File: src/Template/Bake/Model/table.ctp (hunk 3 above)
Comment (josegonzalez) [inline src/Template/Bake/Model/table.ctp]: I mean, if by "doesn't" work, you mean "doesn't autocomplete", then that's fine, no?

File: src/View/Helper/DocBlockHelper.php (hunk 5 above)
Comment (markstory) [inline src/View/Helper/DocBlockHelper.php]: I have no idea. I've not worked in windows environments in a long time.

**Comment by thinkingmedia** [comment]
I have some improvements that can be made to this PR. I'll work on it today.

File: src/View/Helper/DocBlockHelper.php [hunk 8]
```diff
@@ -51,23 +89,49 @@ public function buildEntityPropertyHintTypeMap(array $propertySchema)
...
+     * @return array The property DocType map.
+     */
+    public function buildEntityAssociationHintTypeMap(array $propertySchema)
+    {
+        $properties = [];
+        foreach ($propertySchema as $property => $info) {
+            if ($info['kind'] == 'association') {
+                $type = $this->associatedEntityTypeToHintType($info['type'], $info['association']);
+                if ($info['association']->type() === Association::MANY_TO_ONE) {
+                    $properties = $this->_insertAfter(
```
Comment (ndm2) [inline src/View/Helper/DocBlockHelper.php]: If you split the properties, then doing this isn't necessary anymore, as it is used to position the association properties after the corresponding foreign key properties (`kind = column`).

File: src/Shell/Task/ModelTask.php (hunk 1 above)
Comment (thinkingmedia) [inline src/Shell/Task/ModelTask.php]: it wasn't picked up by phpcs

File: src/Template/Bake/Model/table.ctp [hunk 9]
```diff
@@ -13,34 +13,42 @@
...
 use Cake\Utility\Inflector;
+
+$annotations = [];
+foreach ($associations as $type => $assocs) {
+    foreach ($assocs as $assoc) {
+        $typeStr = Inflector::camelize($type);
+        $annotations[] = "@property \Cake\ORM\Association\\{$typeStr} \${$assoc['alias']}";
+    }
+}
+$annotations[] = "@method {$entity} get(\$primaryKey, \$options = [])";
```
Comment (ndm2) [inline src/Template/Bake/Model/table.ctp]: Should the return types maybe be FQNs? Same for `EntityInterface` in the arguments.

File: src/Template/Bake/Model/table.ctp [hunk 10]
```diff
@@ -13,34 +13,42 @@
...
+$annotations[] = "@method {$entity} newEntity(\$data = null, array \$options = [])";
+$annotations[] = "@method {$entity}[] newEntities(array \$data, array \$options = [])";
+$annotations[] = "@method {$entity} save(EntityInterface \$entity, \$options = [])";
```
Comment (ndm2) [inline src/Template/Bake/Model/table.ctp]: I think this should include `bool`, ie {$entity}`|bool`.

Comment (thinkingmedia) [inline src/Template/Bake/Model/table.ctp]: I'll double check the return types. thanks.

File: src/Template/Bake/Model/table.ctp (hunk 9 above)
Comment (thinkingmedia) [inline src/Template/Bake/Model/table.ctp]: I have no idea on that. I was adding a `use` for those, but if FQN is the preferred way then I'm fine with that.

Comment (ndm2) [inline src/Template/Bake/Model/table.ctp]: The general convention for docblock typehints is to use FQNs, I think it should apply to `@method` too.

**Comment by thinkingmedia** [comment]
I get over 300 warnings from PHPUnit that `getMock` is deprecated. Should I fix this in this PR or ignore it?

**Comment by ADmad** [comment]
> Should I fix this in this PR or ignore it?

A separate PR to fix those would be nice.

File: tests/comparisons/Model/testBakeAssociationDetectionOldProductsTable.php [hunk 11]
```diff
@@ -14,7 +14,7 @@
  * @method OldProduct get($primaryKey, $options = [])
  * @method OldProduct newEntity($data = null, array $options = [])
  * @method OldProduct[] newEntities(array $data, array $options = [])
- * @method OldProduct save(EntityInterface $entity, $options = [])
+ * @method OldProduct| save(EntityInterface $entity, $options = [])
```
Comment (ADmad) [inline tests/comparisons/Model/testBakeAssociationDetectionOldProductsTable.php]: This doesn't look right.

File: src/Template/Bake/Model/table.ctp [hunk 12]
```diff
@@ -13,13 +13,30 @@
...
+foreach ($associations as $type => $assocs) {
+    foreach ($assocs as $assoc) {
+        $typeStr = Inflector::camelize($type);
+        $annotations[] = "@property \Cake\ORM\Association\\{$typeStr} \${$assoc['alias']}";
+    }
+}
+$annotations[] = "@method {$namespace}\\Model\\Entity\\{$entity} get(\$primaryKey, \$options = [])";
+$annotations[] = "@method {$namespace}\\Model\\Entity\\{$entity} newEntity(\$data = null, array \$options = [])";
+$annotations[] = "@method {$namespace}\\Model\\Entity\\{$entity}[] newEntities(array \$data, array \$options = [])";
+$annotations[] = "@method {$namespace}\\Model\\Entity\\{$entity}|bool save(Cake\\Datasource\\EntityInterface \$entity, \$options = [])";
```
Comment (ndm2) [inline src/Template/Bake/Model/table.ctp]: FQNs begin with a leading namespace separator ;)

Comment (thinkingmedia) [inline src/Template/Bake/Model/table.ctp]: Thanks, I'm going to run the plugin on one of my projects and load up the files in the IDE and make sure it all works as expected.
